repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.10
    hooks:
      - id: ruff
        args: [--ignore, "E501", "--fix"]
      - id: ruff-format
        args: [--line-length, "180"]
