name: Deploy to GitHub Pages
permissions:
  contents: write

on:
  push:
    branches:
      - master
  watch:
    types: [started]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository 🛎️
        uses: actions/checkout@v4.1.1

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install and Build 🔧
        run: |
          pnpm install
          pnpm run build

      # - name: Deploy 🚀
      #   uses: JamesIves/github-pages-deploy-action@v4.5.0
      #   with:
      #     folder: build # The folder the action should deploy.
      #     token: ${{ secrets.GH_TOKEN }}
      #     branch: gh-pages
      #     force: true

      - name: Deploy to GitHub Pages 🚀
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          publish_dir: ./build
